# 1Password secret references — safe to commit.
# Run with:  op run --env-file=.env.tpl -- <your command>
# Generated by credential audit 2026-07-30; refs are PREDICTED and
# must be confirmed with ./verify-op-refs.sh before deleting .env.

# Zapier SDK client credentials (used by @zapier/zapier-sdk)
# Generate with:
#   npx zapier-sdk login
#   npx zapier-sdk create-client-credentials "notion-meeting-note-debug"
# The client_secret is shown only once — copy it immediately.
ZAPIER_CLIENT_ID=op://Shared/zapier-workflowers/client id
ZAPIER_CLIENT_SECRET=op://Shared/zapier-workflowers/client secret

# Notion internal integration token (only needed to run the full webhook end-to-end,
# not for the read-only classifier test). Create at:
#   https://www.notion.so/profile/integrations/internal
# NOTION_API_TOKEN=

# Optional: icon-sync webhook the handler POSTs to after updating a Meeting Note.
# ICON_SYNC_WEBHOOK_URL=

# Optional: Zapier connection id for the Jev (TypeSafe) API-by-Zapier connection
# used to classify the meeting Type. Defaults to 02c36cbc-669d-8c82-9c72-7b7813e5cde0.
# ZAPIER_TYPESAFE_CONNECTION_ID=
