# 1Password secret references — safe to commit.
# Run with:  op run --env-file=.env.tpl -- <your command>
# Generated by credential audit 2026-07-30; refs are PREDICTED and
# must be confirmed with ./verify-op-refs.sh before deleting .env.

ICON_SYNC_WEBHOOK_URL=https://www.notion.so/webhooks/worker/9607e18f-5d82-4842-8b96-ca0d32e66011/019e2434-78bd-71c8-b9bf-d170f69e7418/5C6Z6ShQ5qFXUQBh/syncIconFromCompany
NOTION_API_BASE_URL=https://api.notion.com
NOTION_API_TOKEN=op://Shared/notion-workflowers/credential
ZAPIER_CLIENT_ID=op://Shared/zapier-workflowers/client id
ZAPIER_CLIENT_SECRET=op://Shared/zapier-workflowers/client secret
MCP_CLIENT_CONNECTION_ID=025ea818-da55-8691-b4d0-5647c50a0e59
