# 1Password secret references — safe to commit.
# Run with:  op run --env-file=.env.tpl -- <your command>
# Generated by credential audit 2026-07-30; refs are PREDICTED and
# must be confirmed with ./verify-op-refs.sh before deleting .env.

ZAPIER_CLIENT_ID=op://Shared/zapier-workflowers/client id
ZAPIER_CLIENT_SECRET=op://Shared/zapier-workflowers/client secret
