# 1Password secret references — safe to commit.
# Run with:  op run --env-file=.env.tpl -- <your command>
# Generated by credential audit 2026-07-30; refs are PREDICTED and
# must be confirmed with ./verify-op-refs.sh before deleting .env.

# Luma API key — generate on your Luma calendar dashboard
LUMA_API_KEY=op://Shared/luma/credential

# The Luma event to sync guests for (usually starts with evt-)
LUMA_EVENT_ID=evt-bBMVByxIcFBJ1F5
